/// <reference types="@cloudflare/workers-types" />
/// <reference path="./worker/types/cloudflare.d.ts" />

// worker-configuration.d.ts

/* eslint-disable */
// Generated by Wrangler types (customized for TypeScript)

declare namespace Cloudflare {
  interface Env {
    VibecoderStore: KVNamespace;
    TEMPLATES_REPOSITORY: string;
    ALLOWED_EMAIL: string;
    DISPATCH_NAMESPACE: string;
    ANTHROPIC_API_KEY: string;
    OPENAI_API_KEY: string;
    GOOGLE_AI_STUDIO_API_KEY: string;
    OPENROUTER_API_KEY: string;
    CEREBRAS_API_KEY: string;
    GROQ_API_KEY: string;
    SANDBOX_SERVICE_API_KEY: string;
    SANDBOX_SERVICE_TYPE: string;
    SANDBOX_SERVICE_URL: string;
    CLOUDFLARE_API_TOKEN: string;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_AI_GATEWAY_URL: string;
    CLOUDFLARE_AI_GATEWAY_TOKEN: string;
    CLOUDFLARE_AI_GATEWAY: string;
    SERPAPI_KEY: string;
    GOOGLE_CLIENT_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GITHUB_CLIENT_ID: string;
    GITHUB_CLIENT_SECRET: string;
    JWT_SECRET: string;
    ENTROPY_KEY: string;
    ENVIRONMENT: string;
    SECRETS_ENCRYPTION_KEY: string;
    MAX_SANDBOX_INSTANCES: string;
    SANDBOX_INSTANCE_TYPE: string;
    CUSTOM_DOMAIN: string;
    CUSTOM_PREVIEW_DOMAIN: string;
    ALLOCATION_STRATEGY: string;
    GITHUB_EXPORTER_CLIENT_ID: string;
    GITHUB_EXPORTER_CLIENT_SECRET: string;
    CF_ACCESS_ID: string;
    CF_ACCESS_SECRET: string;
    SENTRY_DSN: string;

    // Durable Objects
    CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
    Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
    DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;

    // Storage bindings
    TEMPLATES_BUCKET: R2Bucket;
    DB: D1Database;

    // Rate limiters
    API_RATE_LIMITER: RateLimit;
    AUTH_RATE_LIMITER: RateLimit;

    // AI & Media bindings
    AI: Ai;
    IMAGES: ImagesBinding;

    // Misc
    CF_VERSION_METADATA: WorkerVersionMetadata;
    ASSETS: Fetcher;
    DISPATCHER: DispatchNamespace;
  }
}

// Extend Env globally
interface Env extends Cloudflare.Env {}

// Utility type for NodeJS process.env

type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};

declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<
    Cloudflare.Env,
    | "TEMPLATES_REPOSITORY"
    | "ALLOWED_EMAIL"
    | "DISPATCH_NAMESPACE"
    | "ANTHROPIC_API_KEY"
    | "OPENAI_API_KEY"
    | "GOOGLE_AI_STUDIO_API_KEY"
    | "OPENROUTER_API_KEY"
    | "CEREBRAS_API_KEY"
    | "GROQ_API_KEY"
    | "SANDBOX_SERVICE_API_KEY"
    | "SANDBOX_SERVICE_TYPE"
    | "SANDBOX_SERVICE_URL"
    | "CLOUDFLARE_API_TOKEN"
    | "CLOUDFLARE_ACCOUNT_ID"
    | "CLOUDFLARE_AI_GATEWAY_URL"
    | "CLOUDFLARE_AI_GATEWAY_TOKEN"
    | "CLOUDFLARE_AI_GATEWAY"
    | "SERPAPI_KEY"
    | "GOOGLE_CLIENT_SECRET"
    | "GOOGLE_CLIENT_ID"
    | "GITHUB_CLIENT_ID"
    | "GITHUB_CLIENT_SECRET"
    | "JWT_SECRET"
    | "ENTROPY_KEY"
    | "ENVIRONMENT"
    | "SECRETS_ENCRYPTION_KEY"
    | "MAX_SANDBOX_INSTANCES"
    | "SANDBOX_INSTANCE_TYPE"
    | "CUSTOM_DOMAIN"
    | "CUSTOM_PREVIEW_DOMAIN"
    | "ALLOCATION_STRATEGY"
    | "GITHUB_EXPORTER_CLIENT_ID"
    | "GITHUB_EXPORTER_CLIENT_SECRET"
    | "CF_ACCESS_ID"
    | "CF_ACCESS_SECRET"
    | "SENTRY_DSN"
  >> {}
}

// Optional runtime types that may not be in all Workers type packages
interface RateLimit {
  limit(params: { key: string; weight?: number }): Promise<{
    success: boolean;
    limit: number;
    pending: number;
    reset: string;
  }>;
}

interface Ai {
  run(model: string, options?: AiOptions): Promise<any>;
}

interface AiOptions {
  messages?: AiMessage[];
  prompt?: string;
  stream?: boolean;
  max_tokens?: number;
  temperature?: number;
  [key: string]: any;
}

interface AiMessage {
  role: string;
  content: string;
}

interface ImagesBinding {
  fetch(input: Request | string | URL, init?: RequestInit): Promise<Response>;
}

interface WorkerVersionMetadata {
  commit_hash: string;
  release_tag?: string;
  source: string;
  [key: string]: unknown;
}

interface Fetcher {
  fetch(req: Request | string | URL, init?: RequestInit): Promise<Response>;
}

interface DispatchNamespace {
  get(name: string): { fetch(request: Request | string | URL): Promise<Response> };
}

// Cloudflare global type fallbacks for build environments where module shims are missing
interface DurableObjectState {
  storage: DurableObjectStorage;
  id: DurableObjectId;
  acceptWebSocket(ws: WebSocket, tags?: string[]): void;
  getWebSockets(tag?: string): WebSocket[];
  setWebSocketAutoResponse(pair?: WebSocketRequestResponsePair): void;
  getWebSocketAutoResponse(): WebSocketRequestResponsePair | null;
  getTags(ws: WebSocket): string[];
}

type DurableObjectJurisdiction = 'eu' | 'fedramp';

type DurableObjectLocationHint = 'wnam' | 'enam' | 'weur' | 'eeur' | 'apac' | 'oc';

interface DurableObjectId {
  toString(): string;
  equals(other: DurableObjectId): boolean;
  getName(): string | undefined;
}

interface DurableObjectStub<T = any> {
  get(id: DurableObjectId | string, options?: { locationHint?: DurableObjectLocationHint }): T;
  idFromName(name: string): DurableObjectId;
  idFromString(id: string): DurableObjectId;
  newUniqueId(options?: { jurisdiction?: DurableObjectJurisdiction }): DurableObjectId;
  fetch(request: Request): Promise<Response>;
}

interface DurableObjectNamespace<T = any> {
  idFromName(name: string): DurableObjectId;
  idFromString(id: string): DurableObjectId;
  newUniqueId(options?: { jurisdiction?: DurableObjectJurisdiction }): DurableObjectId;
  get(id: DurableObjectId | string, options?: { locationHint?: DurableObjectLocationHint }): T;
}

type AIGatewayProviders = 'openai' | 'anthropic' | 'google' | 'groq' | 'cerebras' | 'openrouter';

// Cloudflare module augmentation for 'cloudflare:workers' & 'partyserver' targets.
declare module 'cloudflare:workers' {
  interface DurableObject<Env = unknown> {
    ctx: DurableObjectState;
    env: Env;
  }

  interface DurableObjectNamespace<T = unknown> {
    idFromName(name: string): DurableObjectId;
    idFromString(id: string): DurableObjectId;
    newUniqueId(options?: { jurisdiction?: DurableObjectJurisdiction }): DurableObjectId;
    get(id: DurableObjectId | string, options?: { locationHint?: DurableObjectLocationHint }): T;
  }

  interface DurableObjectStub<T = unknown> {
    get(id: DurableObjectId | string, options?: { locationHint?: DurableObjectLocationHint }): T;
    idFromName(name: string): DurableObjectId;
    idFromString(id: string): DurableObjectId;
    newUniqueId(options?: { jurisdiction?: DurableObjectJurisdiction }): DurableObjectId;
    fetch(request: Request): Promise<Response>;
  }
}

declare global {
  type HeadersInit = string[][] | Record<string, string> | Headers;
  interface WebSocketPair {
    0: WebSocket;
    1: WebSocket;
  }
}

